# Generated by Django 5.2.8 on 2026-08-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="partners/", verbose_name="Логотип"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд-партнёр",
                "verbose_name_plural": "Бренды-партнёры",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="price_from",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ориентир стоимости монтажа; пусто — не показывать",
                null=True,
                verbose_name="Цена «от», ₽",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="source",
            field=models.CharField(
                choices=[("form", "Форма обратной связи"), ("quiz", "Калькулятор")],
                default="form",
                max_length=10,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название объекта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-идентификатор"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: складской комплекс, ЖК, офис",
                        max_length=100,
                        verbose_name="Тип объекта",
                    ),
                ),
                ("description", models.TextField(verbose_name="Задача")),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Каждый пункт с новой строки — выводится списком",
                        verbose_name="Что сделано",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="projects/", verbose_name="Фото объекта"
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="catalog.category",
                        verbose_name="Основная категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполненный объект",
                "verbose_name_plural": "Выполненные объекты",
                "ordering": ["order", "-completed_at"],
            },
        ),
    ]
