# Generated by Django 5.2.8 on 2026-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_partner_category_price_from_contactrequest_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="URL-идентификатор"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Короткое описание для списка статей и поисковиков",
                        max_length=500,
                        verbose_name="Анонс",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Абзацы разделяются пустой строкой",
                        verbose_name="Текст статьи",
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=150, verbose_name="Имя клиента"),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: складской комплекс, ООО «Ромашка»",
                        max_length=200,
                        verbose_name="Объект / компания",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
